services:
  - type: web
    name: puja-dairy-udhyog
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: ADMIN_USERNAME
        value: owner
      - key: ADMIN_PASSWORD
        sync: false
