services:
  - type: web
    name: puja-dairy-udhyog
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: OWNER_PASSWORD
        sync: false
      - key: ESEWA_PRODUCT_CODE
        value: EPAYTEST
      - key: ESEWA_SECRET_KEY
        sync: false
